### ISSUE TITLE
Issue in creating storage in the CloudinaryStorage class, specifically the folder section when using typescript

### ISSUE THREAD

**Issue by hazgan72** [affanshahid/multer-storage-cloudinary#56]
When I create storage in the CloudinaryStorage class like this:

const storage = new CloudinaryStorage({
cloudinary,
params: {
folder: 'folder_name',
},
});

The key part of the folder object has an error in typescript like this:
Object literal may only specify known properties, and 'folder' does not exist in type 'Params'.ts(2353)
index.d.ts(21, 5): The expected type comes from property 'params' which is declared here on type 'Options'

then this causes my application to error when I want to build production.

**Comment by xerosine** [comment]
I had the same issue and realized it stemmed from KnownKeys<T> declared after the imports in the index.d.ts file. I got it to work by removing it from the flow by changing 
declare type PickedUploadApiOptions = Pick<UploadApiOptions, KnownKeys<UploadApiOptions>>
to
declare type PickedUploadApiOptions = UploadApiOptions
I know it's not the best fix and would appreciate if anyone could point out what the actual issue was

**Comment by hazgan72** [comment]
Yes, right.
I also found a solution to this problem by using the params object as a function and returning the object { folder: 'name_folder_directory' }
example:
 const storage = new CloudinaryStorage({
    cloudinary,
    params: async (req: Request, res: Response) => {
      return {
        folder: "folder_dir",
      };
    },
  });

but in my opinion it would be better to have an improvement in declaring the typescript in the CloudinaryStorage class
